name: Installing Python

on: [push]

jobs:
  example-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        version: [3.10, 3.11, 3.12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version}}