name: Installing Python

on: [push]

jobs:
  example-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        python-version: [3.1, 3.11, 3.12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version}}